version: '1.0'
updated: '2026-01-24T12:04:52.307141'
processing:
  confidence_threshold: 0.5
  use_gpu: false
  verify_pairs: true
  jpeg_quality: 95
  multi_pass_detection: true
  max_detection_passes: 5
  crop_all: false
ui:
  last_input_dir: /home/pbarros/Pictures/Bill Photos
  last_output_dir: /home/pbarros/Pictures/Bill Photos/fancy_bills
  window_width: 1200
  window_height: 800
  window_x: 544
  window_y: 216
  results_sort_column: position
  results_sort_ascending: true
  show_thumbnails: true
  thumbnail_size: 200
  theme: system
export:
  default_format: csv
  include_thumbnails: true
  excel_template: ''
  html_template: ''
  auto_export_csv: true
  auto_export_summary: true
crop:
  front_seal_x: 0.605
  front_seal_y: 0.233
  front_seal_w: 0.254
  front_seal_h: 0.537
  back_seal_x: 0.635
  back_seal_y: 0.221
  back_seal_w: 0.261
  back_seal_h: 0.557
pattern_states: {}
custom_values: {}
